### PR TITLE
Refactored Layout

### LINKED ISSUE #6: Refactor Layout
I noticed that the general theme, top bar & bottom bar, and the middle body is usually the same through the two links, I recommend refactoring the styles into classes and have a custom Layout where it can be called and the white middle body will be the same. You would do this through react, exporting an custom component through a file like `layout.js`. No need for tailwindcss classes here.

This will make the code more readable and allows for reusablity of previously written code.
Low prioirity. As for we can just copy and paste the front page code to second page and then modify as we please. But this would be a useful task to learn react classes etc.

### PR DESCRIPTION
**Pull request by d3r3j3**
Sorry if variable names are bad.

Closes #6

### CODE REVIEW

**Comment by ericluap** [comment]
I think you might need to do a git pull cause there are some merge conflicts

**Comment by randomlylelo** [comment]
Yep there will be merge conflicts. Just run `npm i` and then keep the package-lock.json that it comes up with
For second page, keep yours but add the three lines to the top of the function.

**Comment by randomlylelo** [comment]
So for `src/SecondPage.js`  make
```js
export default function SecondPage() {
  return (
```

into 

```js
export default function SecondPage() {
  React.useEffect(() => {
        confetti({ colors: [ [ '#fe8c00', '#ffffff' ], [ '#fe8c00', '#ffffff' ] ], timeout: 25 });
    }, []);
  return (
```

and add 
```js
import confetti from "./confetti.js";
```
to the top of the file.

**Comment by randomlylelo** [comment]
Everything else is good though!

**Comment by ericluap** [comment]
yeah should probably still do git pull though cause the most recent commit changed a dependency and that'll make sure it's updated and your commit isn't trying to revert that

**Pull request merged**
